# Generated by Django 3.1.4 on 2020-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pizza_types', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=200, null=True)),
                ('pizza_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=200, null=True)),
                ('topping', models.CharField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn')], max_length=200, null=True)),
            ],
        ),
    ]
